// Turns the Google Fonts CSS in fonts/google.css into fonts/fonts.css and
// downloads the woff2 files beside it. Driven by tools/fetch-fonts.sh.
//
// Vietnamese is dropped and latin + latin-ext kept: the site is English
// with the occasional accented word, and the Vietnamese subset is weight
// this page has no use for. Space Grotesk is a variable font, so one file
// per subset covers 400 through 700.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'fonts');
const css = readFileSync(resolve(dir, 'google.css'), 'utf8');

const blocks = [...css.matchAll(/\/\* (\w[\w-]*) \*\/\s*@font-face \{(.*?)\}/gs)];
const seen = new Set();
const faces = [];
const downloads = new Map();

for (const [, subset, body] of blocks) {
  if (subset === 'vietnamese') continue;
  const family = /font-family: '([^']+)'/.exec(body)[1];
  const weight = /font-weight: (\d+)/.exec(body)[1];
  const range = /unicode-range: ([^;]+);/.exec(body)[1];
  const url = /url\(([^)]+)\)/.exec(body)[1];

  const slug = family.includes('Grotesk') ? 'space-grotesk' : 'space-mono';
  const variable = slug === 'space-grotesk';
  const file = `${slug}-${variable ? 'var' : weight}-${subset}.woff2`;
  if (seen.has(file)) continue;
  seen.add(file);
  downloads.set(file, url);

  faces.push(
    `/* ${family} — ${subset} */\n@font-face {\n` +
      `  font-family: '${family}';\n  font-style: normal;\n` +
      `  font-weight: ${variable ? '400 700' : weight};\n  font-display: swap;\n` +
      `  src: url('${file}') format('woff2');\n  unicode-range: ${range};\n}`
  );
}

for (const [file, url] of downloads) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${file}: ${res.status}`);
  writeFileSync(resolve(dir, file), Buffer.from(await res.arrayBuffer()));
}

const header = `/* Space Grotesk and Space Mono, served from here rather than from Google.
 *
 * Not a performance change. Loading these from fonts.googleapis.com sent
 * every visitor's IP address to a third party before a note was played,
 * which is the one thing this site did that it had no need to do — a
 * Munich court awarded damages over exactly that in January 2022
 * (LG Muenchen I, 3 O 17493/20). Self-hosting removes the request, and
 * with it the disclosure, the consent question, and the dependency.
 *
 * Generated by tools/build-fonts.mjs — do not edit by hand.
 *
 * Both families are under the SIL Open Font License 1.1 — see OFL.txt,
 * which the licence requires to travel with them.
 */

`;
writeFileSync(resolve(dir, 'fonts.css'), header + faces.join('\n\n') + '\n', 'utf8');
console.log(`wrote fonts/fonts.css — ${faces.length} faces, ${downloads.size} files`);
