// Writes js/build.js, which is the only way to know what a glitch report
// was actually running.
//
// GitHub Pages and the browser both cache, so a phone can be several
// commits behind while reporting against the newest code — which happened,
// and cost a round of debugging: a report came back carrying a fault that
// had already been fixed, and there was no way to tell from the report
// itself. Run before committing.

import { writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const stamp = new Date().toISOString().replace(/\.\d+Z$/, 'Z').replace('T', ' ');
// HEAD as it stands now, which is the commit *before* the one being made.
// Named accordingly, so it is never mistaken for the running commit.
let after = 'unknown';
try {
  after = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim();
} catch (_) { /* not a checkout */ }

writeFileSync(
  resolve(root, 'js/build.js'),
  `// Generated by tools/stamp-build.mjs — do not edit.\n` +
    `export const BUILD = { at: '${stamp}', after: '${after}' };\n`,
  'utf8'
);
console.log(`stamped build ${stamp} (after ${after})`);
